services:
  backend:
    build:
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "22112:22112"
    volumes:
      - ./src/backend/data/:/app/data
    environment:
      - DATA_DIR=/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:22112/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ./src/frontend
      dockerfile: Dockerfile
    ports:
      - "22111:22111"
    environment:
      - API_URL=http://backend:22112
      - PORT=22111
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:22111/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  default:
    name: devops-net
