#!/bin/bash

# Aktiviere mise, um Python im PATH zu haben
eval "$(mise activate bash)"

if ! command -v cz >/dev/null && [ "$DEVPOD" = "true" ]; then
  git config --global push.autoSetupRemote true
  git config --global --add safe.directory /workspaces/$(basename $(pwd))
  
  # Tools direkt mit pipx installieren (keine venv nötig)
  pip install --user pipx
  export PATH="$HOME/.local/bin:$PATH"
  
  # Tools installieren
  pipx install commitizen
  pipx install pre-commit
  pip install ruff
  
  # Git-Hooks einrichten
  pre-commit install
  pre-commit install --hook-type commit-msg
fi