name: Backend Tests

on:
  pull_request:
    paths:
      - 'devops-projekt/src/backend/**'              # ✅ Full path to your backend
      - '.github/workflows/backend-tests.yaml'
      - 'devops-projekt/mise.toml'
  push:
    branches: [main]
    paths:
      - 'devops-projekt/src/backend/**'

jobs:
  test:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./devops-projekt/src/backend   # ✅ Full path

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python 3.12
        run: uv python install 3.12

      - name: Install dependencies
        run: uv sync --locked --dev

      - name: Lint with Ruff
        run: |
          uv run ruff check --output-format=github --target-version=py312 src tests
          uv run ruff format --diff --check --target-version=py312 src tests

      - name: Run Tests
        run: |
          uv run pytest tests/ -v --cov=src --cov-report=xml
