name: Backend Tests

on:
  pull_request:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'src/backend/**'               # ✅ Korrekt für dein repo
              - '.github/workflows/backend-tests.yaml'

  test:
    name: Test Backend
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend      # ✅ Korrekt für dein repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: |
          uv sync --group dev                 # ✅ Modern dependency groups

      - name: Lint with Ruff
        run: |
          uv run --group dev ruff check --output-format=github --target-version=py312 src tests
          uv run --group dev ruff format --diff --check --target-version=py312 src tests
