name: Backend Tests

on:
  pull_request:  ### triggert nur bei pull requests !
    paths:
      - 'src/backend/**'
      - '.github/workflows/backend-tests.yaml'
  push:
    branches: [main]          # ← Nur noch diese Zeile!
  workflow_dispatch:

jobs:
  check_paths:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.filter.outputs.backend }}
    steps:
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3.0.2
        id: filter
        with:
          filters: |
            backend:
              - 'src/backend/**'
              - '.github/workflows/backend-tests.yaml'

  test:
    name: Test Backend
    needs: check_paths
    if: ${{ needs.check_paths.outputs.should_run == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install UV
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install 3.12

      - name: Install dependencies
        run: |
          uv sync --group dev

      - name: Debug - Check installation
        run: |
          pwd
          ls -la
          echo "Python version: $(uv run python --version)"
          echo "Ruff version: $(uv run --group dev ruff --version)"

      - name: Lint with Ruff
        run: |
          uv run --group dev ruff check --output-format=github --target-version=py312 src tests
          uv run --group dev ruff format --diff --check --target-version=py312 src tests

      - name: Run tests with coverage
        run: |
          uv run pytest tests/ -v --cov=src --cov-report=xml --cov-report=term-missing

      - name: Build Docker image
        run: docker build -t backend-app:latest .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          image-ref: "backend-app:latest"
          format: "table"
          exit-code: "0"
          # exit-code: '1' # Fail the workflow if vulnerabilities are found.
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL,HIGH"

      - name: Upload Coverage
        uses: codecov/codecov-action@v4
        if: always()
        with:
          file: ./src/backend/coverage.xml
          directory: ./src/backend
          fail_ci_if_error: false