name: Update GitOps Repository

on:
  workflow_call:
    inputs:
      tag:
        required: true
        type: string
        description: "The tag name of the release"
      image:
        required: true
        type: string
        description: "The image being updated"
    secrets:
      GITOPS_DEPLOY_KEY:
        required: true
        description: "Deploy key for GitOps repository"
      DEVOPS_STUDY_APP:
        required: true
        description: "PAT GitOps repository"

jobs:
  update-gitops:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Actions Repo
        uses: actions/checkout@v4
        with:
          path: actions-repo

      - name: Checkout GitOps repository
        uses: actions/checkout@v4
        with:
          repository: Tim275/mindset-app-gitops
          ref: main
          path: mindset-app-gitops
          ssh-key: ${{ secrets.GITOPS_DEPLOY_KEY }}

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Update Image Tags Dev
        run: |
          # Define the target kustomization file
          KUSTOMIZATION_FILE="./mindset-app-gitops/apps/dev/kustomization.yaml"  
          SCRIPT_PATH="./actions-repo/scripts/update_kustomize_tag"

          # Make script executable
          chmod +x "$SCRIPT_PATH"

          # Call the script with the input tag, kustomization file path, and image name
          echo "Calling update script with tag: ${{ inputs.tag }}, file: $KUSTOMIZATION_FILE, image: ${{ inputs.image }}"
          "$SCRIPT_PATH" "${{ inputs.tag }}" "$KUSTOMIZATION_FILE" "${{ inputs.image }}"

      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitOps Bot
          author_email: gitops-bot@github.com
          cwd: ./mindset-app-gitops
          message: Update ${{ inputs.image }} deployment with tag "${{ inputs.tag }}"

      - name: Update Image Tags Prod
        run: |
          # Define the target kustomization file
          KUSTOMIZATION_FILE="./mindset-app-gitops/apps/prod/kustomization.yaml"
          SCRIPT_PATH="./actions-repo/scripts/update_kustomize_tag"

          # Call the script with the input tag, kustomization file path, and image name
          echo "Calling update script with tag: ${{ inputs.tag }}, file: $KUSTOMIZATION_FILE, image: ${{ inputs.image }}"
          "$SCRIPT_PATH" "${{ inputs.tag }}" "$KUSTOMIZATION_FILE" "${{ inputs.image }}"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.DEVOPS_STUDY_APP }}
          path: ./mindset-app-gitops
          commit-message: Update prod deployments to tag ${{ inputs.tag }}
          committer: GitOps Bot <gitops-bot@github.com>
          author: GitOps Bot <gitops-bot@github.com>
          branch: gitops/update-tag-${{ inputs.image }}
          delete-branch: true
          title: "Update prod image tag to ${{ inputs.tag }}"
          body: |
            Update image tag in the prod environment kustomization for ${{ inputs.image }}.
          labels: |
            automated-pr
            gitops